"""empty message

Revision ID: 072c9eaf754b
Revises: ae908ef4296f
Create Date: 2022-05-27 10:19:57.037924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072c9eaf754b'
down_revision = 'ae908ef4296f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_token', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'api_token')
    # ### end Alembic commands ###
